export const eventsInfo = [
    {
        venue: "Essen@Anchorvale",
        partners: ["Little Band Plus"],
        startTime: "7.30pm",
        endTime: "10.30pm",
        date: "Every Sun",
        genres: ["Mandopop", "Cantopop", "Top 40"],
        googleUrl: "https://goo.gl/maps/mphFkRoHpkw2XZZ98",
        websiteUrl: "https://essensg.wixsite.com/essen",
    },
    {
        venue: "Relax Bar",
        partners: ["Tingzhi"],
        startTime: "8pm",
        endTime: "11pm",
        date: "Every Tue",
        genres: ["Mandopop", "Cantopop", "Top 40"],
        googleUrl: "https://goo.gl/maps/PkFo47oHM7wEvP9Y9",
        websiteUrl: "https://www.facebook.com/relaxbistrobar/",
    },
    {
        venue: "Tenplus",
        partners: ["Natalie Tan"],
        startTime: "7pm",
        endTime: "10pm",
        date: "Every Wed",
        genres: ["Mandopop", "Cantopop", "Top 40"],
        googleUrl: "https://goo.gl/maps/XWfArM2ktef6SREF8",
        websiteUrl: "https://www.tenplus.sg/",
    },
    {
        venue: "Tenplus",
        partners: ["Tingzhi"],
        startTime: "7pm",
        endTime: "10pm",
        date: "Every Fri",
        genres: ["Mandopop", "Cantopop", "Top 40"],
        googleUrl: "https://goo.gl/maps/XWfArM2ktef6SREF8",
        websiteUrl: "https://www.tenplus.sg/",
    },
    {
        venue: "JJAN",
        partners: ["Serena Chen"],
        startTime: "7.30pm",
        endTime: "10.30pm",
        date: "Every Sat",
        genres: ["Mandopop", "Cantopop", "Top 40"],
        googleUrl: "https://maps.app.goo.gl/LkCKumfTSwYtJdU69",
        websiteUrl: "https://www.instagram.com/jjansg/?hl=en",
    },
];
