import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Music Sheet | Isaac Yong's Official Website | 楊征宇 官方網站",
    description: "Generated by Next.js",
};

export { default } from "./MusicSheets";
