import "@/styles/globals.scss";
import Provider from "./Provider";
import NavigationBar from "@/src/components/NavigationBar";
import Footer from "@/src/components/Footer";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Provider>
                <NavigationBar isSticky={false} />
                <body>{children}</body>
                <Footer />
            </Provider>
        </html>
    );
}
